### ISSUE TITLE
Unable to create stack

### ISSUE THREAD

**Issue by pociej** [Akord-com/akord-js#212]
Wehn trying to uplad file it throws me 

```
53 |                 throw new bad_request_1.BadRequest("File name is required, please provide it in the file options.");
54 |             }
55 |             if (!mimeType) {
56 |                 console.warn("Missing file mime type. If this is unintentional, please provide it in the file options.");
57 |             }
58 |             this.name = name;
                ^
TypeError: Attempted to assign to readonly property.
      at new File (/Users/dzik/Projects/playground/christmas_nft/backend/node_modules/@akord/akord-js/lib/types/file.js:58:12)
      at /Users/dzik/Projects/playground/christmas_nft/backend/node_modules/@akord/akord-js/lib/types/file.js:92:33
      at fulfilled (/Users/dzik/Projects/playground/christmas_nft/backend/node_modules/@akord/akord-js/lib/types/file.js:28:47)
      at processTicksAndRejections (:61:7
```

**Comment by pociej** [comment]
EDIT: it happens only when running by bun. With node everything is ok.
